### ISSUE TITLE
CharsetEncoder.prototype.s2u unknown char just continue, not throw

### ISSUE THREAD

**Issue by suboy** [takahirox/mmd-parser#1]
In 'CharsetEncoder.prototype.s2u'

    if(t[key] === undefined) {
      throw 'unknown char code ' + key + '.';
    }

Maybe just console.log('unknown char code ' + key + '.') and continue will be better.
some special ModelName or Comment words maybe not in the s2uTable.

**Comment by takahirox** [comment]
I updated `charset-encoder-js` to do so, thanks.
